feat(liquid): add new plot liquid
antvis/G2Plot pull request #1499
Opened 2020-08-28 11:39 UTC by hustcc

- [x] 类型定义
 - [x] 图形绘制
 - [ ] 动画问题
 - [ ] 动画的一些配置暴露（暂时不暴露）

2020-08-28 23:51 UTC, Me-Momo requested changes

2020-08-28 23:51 UTC, Me-Momo commented on src/plots/liquid/adaptor.ts
> + * 折线图适配器
文案：水波图

2020-08-28 23:51 UTC, Me-Momo commented on src/utils/g-util.ts
>    const matrix = Util.transform(ulMatrix, actions);
`Util.transform` 等价于 `ext.transform` 看下保留哪个？

2020-08-28 23:51 UTC, Me-Momo commented on src/utils/g-util.ts
> +  return ext.transform(ulMatrix, actions);
感觉和上面 groupTransform  的区别有两点
1、是否传入原始 matrix（通过 默认参数 解决）
2、是否主动 setMatrix（这个看下怎么辨识，现在函数名无法得知）

2020-08-29 05:13 UTC, hustcc commented on src/utils/g-util.ts
> +  return ext.transform(ulMatrix, actions);
这个也是直接从 v1 抄过来的方法。水波图里面用到一个，我会整理一下看看~

2020-09-04 06:01 UTC, hustcc commented on src/utils/g-util.ts
>    const matrix = Util.transform(ulMatrix, actions);
保留了 Util。

2020-09-04 06:20 UTC, Me-Momo approved these changes

2020-09-04 07:55 UTC, merged