fix: issue 1727
antvis/G2Plot pull request #1730
Opened 2020-10-15 11:02 UTC by lxfu1

- fix 1727
- 新增 tooltip formatter [1724]
- 抽取 percent customContent

2020-10-15 12:30 UTC, Me-Momo requested changes

2020-10-15 12:30 UTC, Me-Momo commented on __tests__/bugs/issue-1727-spec.ts
> +    const radar = new Radar(createDiv('area tooltip 重复'), {
nit: area tooltip 重复

2020-10-15 12:30 UTC, Me-Momo commented on src/plots/radar/adaptor.ts
> +  if (!label) {
`label === false`

2020-10-15 12:30 UTC, Me-Momo commented on __tests__/bugs/issue-1727-spec.ts
> +import { Radar } from '../../src';
建议在 unit/plots/radar 下增加 `legend-spec` 和 `label-spec` 即可

2020-10-15 12:38 UTC, hustcc commented on src/utils/tooltip.ts
> +export function transformTooltip(tooltipConfig: any, isPercent?: boolean) {
tooltipConfig  -> tooltipOption

2020-10-15 12:41 UTC, hustcc commented
tooltip.formatter 的单测。包括 util 中的几个 transform 函数的单测。

2020-10-15 13:37 UTC, lxfu1 commented on src/plots/radar/adaptor.ts
> +  if (!label) {
这个直接判断 false 会遗漏，例如 null、undefined等，感觉不友好。

2020-10-15 13:39 UTC, lxfu1 commented
> tooltip.formatter 的单测。包括 util 中的几个 transform 函数的单测。

utils/transform-tooltip-spec.ts
plots/radar/tooltip-spec.ts

2020-10-16 01:50 UTC, hustcc approved these changes

2020-10-16 01:51 UTC, hustcc approved these changes

2020-10-16 01:52 UTC, merged