docs: 图表组件 api 整理
antvis/G2Plot pull request #2308
Opened 2021-02-04 14:03 UTC by ntscshen

### PR includes

- [x] documents, demos

### Screenshot

![image](https://user-images.githubusercontent.com/21041458/106902027-514e2180-6733-11eb-8d61-62c603b8a237.png)

---------
1. 为什么把很多data数据中的，type字段改成了name，我是怎么理解的
> G2中"声明度量类型"字段为 `type` ，G2Plot封装中默认使用的 `colorField`，不过这个name字段可能不合适 😳 ，如果不符合预期明天再改一波
```js
// G2Plot/src/plots/pie/adaptor.ts
/**
 * meta 配置
 * @param params
 */
function meta(params: Params<PieOptions>): Params<PieOptions> {
  const { chart, options } = params;
  const { meta, colorField } = options;

  // meta 直接是 scale 的信息
  const scales = deepAssign({}, meta);
  chart.scale(scales, {
    [colorField]: { type: 'cat' },
  });

  return params;
}
```

2021-02-04 14:07 UTC, visiky requested changes

2021-02-04 14:07 UTC, visiky commented on docs/manual/plots/pie.en.md
> +  { name: '其他', value: 5 },
为什么要修改这个？没有区别啊，在这个数据集中，确实 key 值是 `type` 代表分类

2021-02-04 14:07 UTC, visiky commented on docs/manual/plots/pie.en.md
> +  colorField: 'name',
just a key of field

2021-02-04 14:08 UTC, visiky commented
> ### PR includes
> * [x]  documents, demos
> 
> ### Screenshot
> ![image](https://user-images.githubusercontent.com/21041458/106902027-514e2180-6733-11eb-8d61-62c603b8a237.png)
> 
> 1. 为什么把很多data数据中的，type字段改成了name，我是怎么理解的
> 
> > G2中"声明度量类型"字段为 `type` ，G2Plot封装中默认使用的 `colorField`，不过这个name字段可能不合适 😳 ，如果不符合预期明天再改一波
> 
> ```js
> // G2Plot/src/plots/pie/adaptor.ts
> /**
>  * meta 配置
>  * @param params
>  */
> function meta(params: Params<PieOptions>): Params<PieOptions> {
>   const { chart, options } = params;
>   const { meta, colorField } = options;
> 
>   // meta 直接是 scale 的信息
>   const scales = deepAssign({}, meta);
>   chart.scale(scales, {
>     [colorField]: { type: 'cat' },
>   });
> 
>   return params;
> }
> ```

不需要这些修改，`colorField` 只是代表切片分类字段，不管是 type 还是 name，还是 country 还是 city 等等，没有含义

2021-02-05 02:22 UTC, ntscshen commented on docs/manual/plots/pie.en.md
> +  { name: '其他', value: 5 },
说的倒是，我把他回退了

2021-02-05 07:56 UTC, closed without merging