feat: add polar attribute to heatmap
antvis/G2Plot pull request #2425
Opened 2021-03-12 08:17 UTC by aiqinghai12

添加极坐标属性到heatmap 热力图/色块图。  并添加 例子。

2021-03-16 03:13 UTC, visiky requested changes

2021-03-16 03:13 UTC, visiky commented on docs/api/plots/heatmap.en.md
> +#### polar
四级标题上下留空白行

2021-03-16 03:13 UTC, visiky commented on docs/api/plots/heatmap.en.md
>  #### sizeRatio
同上，留空白行

2021-03-16 03:13 UTC, visiky commented on docs/api/plots/heatmap.zh.md
> +#### polar
留空白行

2021-03-16 03:13 UTC, visiky commented on src/plots/heatmap/adaptor.ts
> +    chart.coordinate('polar', {
一旦支持 polar，势必会有需求 希望支持 radius、innerRadius的配置。不如直接就是 coordinate 的配置项？

2021-03-17 03:24 UTC, aiqinghai12 commented on docs/api/plots/heatmap.zh.md
> +#### polar
已经修改好了

2021-03-17 03:25 UTC, aiqinghai12 commented on src/plots/heatmap/adaptor.ts
> +    chart.coordinate('polar', {
已经直接用coordinate,并把上面的reflect 放到下面

2021-03-17 03:26 UTC, aiqinghai12 commented on docs/api/plots/heatmap.en.md
>  #### sizeRatio
已经修改

2021-03-17 03:26 UTC, aiqinghai12 commented on docs/api/plots/heatmap.en.md
> +#### polar
已经修改

2021-03-17 03:34 UTC, visiky commented on __tests__/unit/plots/heatmap/coordinate-spec.ts
> +      coordinate: {
默认没有设置就是 rect，可以在单测中 把这个配置移除，然后判定获取坐标系还是 rect

2021-03-17 03:34 UTC, visiky commented on docs/api/plots/heatmap.en.md
> +<description>**optional** </description>
类型定义， _CoordinateCfg_

**_CoordinateCfg_** 配置项如下：

从 G2 拷贝下

2021-03-17 03:34 UTC, visiky commented on src/plots/heatmap/adaptor.ts
> +  if (reflect) {
reflect 写在后边

2021-03-17 05:58 UTC, aiqinghai12 commented on docs/api/plots/heatmap.en.md
> +<description>**optional** </description>
迁移好了

2021-03-17 05:59 UTC, aiqinghai12 commented on __tests__/unit/plots/heatmap/coordinate-spec.ts
> +      coordinate: {
已经修改

2021-03-17 07:40 UTC, hustcc commented on src/plots/heatmap/types.ts
>    readonly reflect?: 'x' | 'y';
这个配置直接干掉吧~

2021-03-17 07:40 UTC, hustcc commented on src/plots/heatmap/adaptor.ts
> +      cfg: coordinate?.cfg,
上面判断了 coordinate 存在，所以这里就不加 ? 吧！

2021-03-17 08:18 UTC, visiky approved these changes

2021-03-17 08:19 UTC, merged