docs(dualbarmix): 修复双轴图的API文档-图形样式中的链接和国际化问题
antvis/G2Plot pull request #2531
Opened 2021-04-29 11:11 UTC by DawnLck

### PR includes

- [ ] fixed #0
- [ ] add / modify test cases
- [x] documents, demos

### Screenshot

|  Before  |  After  |
|----|----|
|  ❌  |  ✅  |

2021-04-29 13:08 UTC, visiky requested changes

2021-04-29 13:08 UTC, visiky commented on docs/api/plots/dual-axes.en.md
> +| smooth       | _boolean_                        | Whether is smooth [Line smooth](../../docs/api/plots/line#smooth)                                                               | false   |
🙇‍♀️ 辛苦这里改成: 绝对路径 `en/docs/api/plots/line#seriesfield`, `zh/docs/api/plots/line#seriesfield` 同理，其他

2021-04-29 16:05 UTC, DawnLck commented on docs/api/plots/dual-axes.en.md
> +| smooth       | _boolean_                        | Whether is smooth [Line smooth](../../docs/api/plots/line#smooth)                                                               | false   |
Get it

2021-05-02 01:04 UTC, visiky approved these changes

2021-05-02 01:05 UTC, merged