feat(violin): 添加小提琴图
antvis/G2Plot pull request #2569
Opened 2021-05-21 03:47 UTC by YiSiWang

### PR includes

- [x] add violin
- [x] add / modify test cases
- [x] documents, demos

2021-05-21 03:50 UTC, YiSiWang commented
Demo 里，有 BasicDemo 和 GroupDemo （分组和不分组），它们共用一份 data 。
目前是写的两份，因为 Demo 代码可能不能引外部文件？

2021-05-21 04:29 UTC, visiky requested changes

2021-05-21 04:29 UTC, visiky commented on __tests__/unit/plots/violin/box-spec.ts
> +    expect(medianView).toBeUndefined();
note: 可以理解为小提琴图的分布数据（箱型图）由 3 个 view 组成：最大最小值、中位数、上下四分位数

2021-05-21 04:29 UTC, visiky commented on docs/api/plots/violin.en.md
> +Make viollin shapes hollow. Defaults to false.
smooth 和 hollow 是否直接 shape 支持就好, @hustcc 虽然折线图是直接：smooth 一个配置项，但是 hollow 不应该再放开了（是否在小提琴图这里，考虑集中在一起）
`shape?: 'smooth' | 'hollow-smooth' | 'hollow'`

2021-05-21 04:29 UTC, visiky commented on docs/api/plots/violin.en.md
> +  textMap?: {
![image](https://user-images.githubusercontent.com/15646325/119081599-e5b46980-ba2e-11eb-94c5-49cc62a5e4f7.png)

@hustcc 是否需要提供这样的配置，还是让用户自己去 tooltip 自定义即可？如果需要的话，箱线图也需要

![image](https://user-images.githubusercontent.com/15646325/119081649-02e93800-ba2f-11eb-923c-a59c9f32c400.png)

2021-05-21 04:29 UTC, visiky commented on package.json
> +    "pdfast": "^0.2.0",
pdfast 这是什么，这两个包加进去后；本地 build 打包大小 超过限制了没

2021-05-21 04:29 UTC, visiky commented on src/plots/violin/adaptor.ts
> +import { interaction, animation, theme } from '../../adaptor/common';
state 是否可以加？

2021-05-21 04:29 UTC, visiky commented on src/plots/violin/adaptor.ts
> +  chart.tooltip({
```ts
chart.tooltip(deepAssign({}, { /** 内置的 */ }, tooltip /** 用户配置的*/ ))
```

2021-05-21 04:29 UTC, visiky commented on src/plots/violin/adaptor.ts
> +      lineWidth: 0,
用户是否可配置

2021-05-21 04:29 UTC, visiky commented on src/plots/violin/adaptor.ts
> +  g.position(`x*${VIOLIN_Y}`)
`VIOLIN_Y` 都有了，为什么 `x` 不抽取一个通用常量 `X'_FIELD`

2021-05-21 04:29 UTC, visiky commented on src/plots/violin/constant.ts
> +export const VIOLIN_Y = 'violinY';
考虑到会暴露出去在业务层使用，换成: `X_FIELD`, `Y_FIELD`, `SERIES_FIELD`(还是 `COLOR_FIELD` 呢）@hustcc

2021-05-21 06:13 UTC, YiSiWang commented on package.json
> +    "pdfast": "^0.2.0",
这里有个 TODO ，看一下引入 `pdfast` 和 `simple-statistics` 后的包大小变化。

（`pdfast` 本身源码就很少，目测它影响不大）

2021-05-21 06:20 UTC, YiSiWang commented on src/plots/violin/adaptor.ts
> +      lineWidth: 0,
目前是不可以的，要加的话，加载 `box` 选项里：

```ts
box: {
  textMap: { ... },
  medianStyle: { ... },
}
```

但是小提琴中的箱线图要有哪些配置项呢？
我现在没想清楚，甚至四分位点、上下边缘线的位置是否能定义也迷茫（G2Plot 带不带这些数据处理？）。

2021-05-21 06:23 UTC, YiSiWang commented on src/plots/violin/adaptor.ts
> +  g.position(`x*${VIOLIN_Y}`)
我加上吧

2021-05-21 06:23 UTC, YiSiWang commented on src/plots/violin/adaptor.ts
> +import { interaction, animation, theme } from '../../adaptor/common';
`state`是什么？有参考吗

2021-05-22 03:48 UTC, visiky commented
> Demo 里，有 BasicDemo 和 GroupDemo （分组和不分组），它们共用一份 data 。
> 
> 目前是写的两份，因为 Demo 代码可能不能引外部文件？

上传到cdn，通过fetch获取

2021-05-24 08:00 UTC, YiSiWang commented on package.json
> +    "pdfast": "^0.2.0",
`pdfast` 只有2K，`simple-statistics` tree-shaking 有问题，改用源码了。

![image](https://user-images.githubusercontent.com/20316342/119316133-29b2a300-bca9-11eb-8e22-4eeb391c77e6.png)

2021-05-24 08:52 UTC, YiSiWang commented
> > Demo 里，有 BasicDemo 和 GroupDemo （分组和不分组），它们共用一份 data 。
> > 目前是写的两份，因为 Demo 代码可能不能引外部文件？
> 
> 上传到cdn，通过fetch获取

Done

2021-05-24 10:05 UTC, visiky commented on docs/api/plots/violin.en.md
> +Make viollin shapes hollow. Defaults to false.
⚠️ 改成：`shape`

2021-05-24 10:05 UTC, visiky commented on src/plots/violin/constant.ts
> +export const VIOLIN_Y = 'violinY';
⚠️ 改掉

2021-05-24 12:05 UTC, YiSiWang commented on src/plots/violin/constant.ts
> +export const VIOLIN_Y = 'violinY';
VIOLIN_Y 是小提琴的概率密度通道，不是 Y_FIELD

2021-05-25 08:02 UTC, visiky commented on docs/api/plots/violin.en.md
> +  textMap?: {
文档里边说明下：小提琴图内置了箱形图作为分布统计展示，提供 5 个基础数据，分别为：low（最低值）、q1....

另外，说下这些字段可以在 meta 中进行设置，然后提供一个 demo 展示如何进行别名设置以及数值的格式化

抄送： @hustcc

2021-05-28 16:48 UTC, merged

2021-06-15 22:11 UTC, visiky commented
@all-contributors please add @YiSiWang  for code