refactor(pixel-plot): 添加和初始化三层canvas画布
antvis/G2Plot pull request #2691
Opened 2021-07-12 07:59 UTC by Angelii

### PR includes

- [ ] fixed #0
- [ ] add / modify test cases
- [ ] documents, demos

### Screenshot

|  Before  |  After  |
|----|----|
|  ❌  |  ✅  |

2021-07-12 08:56 UTC, pearmini requested changes

2021-07-12 08:56 UTC, pearmini commented on src/pixels/canvas.ts
> +  /** 像素图包围盒 */
前面用的 bgCanvas，后面用的 foreCanvas，感觉命名不太统一？用 fgCanvas 感觉要合适一点？或者改成 backCanvas？

2021-07-12 09:04 UTC, visiky commented on src/pixels/canvas.ts
> +  /** 像素图包围盒 */
`backCanvas` 把

2021-07-12 09:07 UTC, Angelii commented on src/pixels/canvas.ts
> +  /** 像素图包围盒 */
嗯嗯，可以~

2021-07-12 09:10 UTC, visiky commented on src/pixels/canvas.ts
> +    this.options = { ...DEFAULT_OPTIONS, ...options };
用 deepMix 进行 合并

2021-07-12 09:10 UTC, visiky commented on src/pixels/canvas.ts
> +    this.bgCanvas.cfg.el.id = 'bg-canvas';
G 应该有方法可以给他设置 id？

2021-07-12 09:10 UTC, visiky commented on src/pixels/canvas.ts
> +    this.bgCanvas.cfg.el.id = 'bg-canvas';
最坏的情况是: `bgCanvas.get('el').id = 'bg-canvas'`

2021-07-12 09:18 UTC, visiky commented on src/pixels/canvas.ts
> +    foreCanvasStyle.left = '0px';
和 midCanvas 存在较多重复代码，可以考虑封装一个纯 util 方法，mutable
的方式处理 canvas 的样式，比如：
```ts
function setCanvasPosition(canvas: HTMLCanvasElement, top: number, left: number) {

}
```

2021-07-12 09:18 UTC, visiky commented on src/pixels/components/tooltip.ts
> +import { PixelPlot } from '../index';
一般不要直接从 index 获取内容，目录结构可以考虑如下：
```ts
- src/pixels
    - type.ts
    - util.ts
    - components/
    - ....

```

2021-07-12 09:25 UTC, visiky commented on src/pixels/canvas.ts
> +  /** 像素图包围盒 */
统一下:
```ts
  /** 三层 Group 图形中的背景层。 */
  public backgroundCanvas Canvas;
  /** 三层 Group 图形中的中间层。 */
  public middleCanvas: HTMLCanvasElement;
  /** 三层 Group 图形中的前景层。 */
  public foregroundCanvas: Canvas;
```

2021-07-14 11:25 UTC, visiky approved these changes

2021-07-26 06:14 UTC, visiky commented
存在点冲突，解决之后 我就合并了

2021-07-28 12:12 UTC, closed without merging