feat: 增加 pattern 贴图
antvis/G2Plot pull request #2777
Opened 2021-08-09 10:39 UTC by visiky

### PR includes

- [ ] fixed #0
- [ ] add / modify test cases
- [ ] documents, demos

### Screenshot

|  Before  |  After  |
|----|----|
|  ❌  |  ✅  |

2021-08-10 03:29 UTC, pearmini reviewed
感觉可以写的更加简洁一点 🤣

2021-08-10 13:24 UTC, pearmini requested changes

2021-08-10 13:24 UTC, pearmini commented on src/utils/pattern/dot.ts
> +  );
这里感觉没有必要这么写吧？感觉可以直接解构  + 默认值，并且上层可以统一创建一个 canvas 传进来，并且不用把 canvas 返回了 ？

```js
// dot.js
 export function createDotPattern(canvas, {
  radius=20,
  bgColor='transparent',
  opacity=1,
  fill='#FFF',
  fillOpacity=1,
  padding=5,
  stroke='transparent',
  strokeWidth=0,
  isStagger=true,
}: DotPatternOptions) {
  const size = (radius + padding) * (isStagger ? 4 : 2);
  const halfSize = size / 2;
  const quarterSize = size / 4;
  const dots = isStagger ? [
      [quarterSize * 1, quarterSize * 1],
      [quarterSize * 3, quarterSize * 1],
      [quarterSize * 0, quarterSize * 3],
      [quarterSize * 2, quarterSize * 3],
      [quarterSize * 4, quarterSize * 3]
    ] : [
      [halfSize, halfSize]
    ];
  
  const context = canvas.getCanvas('2d');
  canvas.width = size;
  canvas.height = size;
  context.globalAlpha = opacity;
  context.fillStyle = bgColor;
  context.fillRect(0, 0, size, size);
  
  for (const [x, y] of dots) {
    context.beginPath();
    context.fillStyle = fill;
    context.strokeStyle = stroke;
    context.lineWidth = strokeWidth;
    context.arc(x, y, radius, 0, 2 * Math.PI);
    context.fill();
    context.stroke();
  }
}
```
```js
// index.js
import {dot} from "./dot.js";
import {line} from "./line.js";

const SHAPE_TYPE = {
  line,
  dot,
}
  
export function createPattern(options) {
  const { type, cfg={} } = options;
  const patternCanvas = document.createElement('canvas');
  const patternContext = patternCanvas.getContext('2d');
  const shape = createShape(type, cfg);
  const pattern = patternContext.createPattern(shape, cfg.mode || 'repeat');
  return pattern;
}

function createShape(type, cfg) {
  const canvas = document.createElement('canvas');
  const shape = SHAPE_TYPE[type];
  if (!shape) throw new Error(`unknown pattern type: ${type}`);
  else shape(canvas, cfg);
  return canvas;
}
```

2021-08-12 02:37 UTC, visiky commented on src/utils/pattern/index.ts
> +    pattern.setTransform({ a: 1 / dpr, b: 0, c: 0, d: 1 / dpr, e: 0, f: 0 });
其实这个处理 应该在 createPattern 的地方增加 🤔 因为是在create的时候被放大了，所以需要在那个过程中把pattern还原初始尺寸

2021-08-12 02:38 UTC, visiky commented on examples/plugin/pattern/demo/column-pattern.ts
> +      mode: 'repeat',
demo 原则是简单，默认配置已经是 repeat 了，就不需要设置了. 倒是可以考虑考虑一些没repeat的贴图应该会是怎样的 来进行展示

2021-08-15 04:47 UTC, visiky commented
|||
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/129467447-d1021f15-f2f6-4300-b664-89ea0256fb2a.png)|![image](https://user-images.githubusercontent.com/15646325/129467451-138e6a9e-071b-4f00-8b49-dd07d53874cf.png)|

2021-08-19 11:13 UTC, visiky commented on src/types/attr.ts
> +  | boolean
这个是为什么要加 `boolean` @Angelii

2021-08-24 01:52 UTC, merged