Refactor pattern
antvis/G2Plot pull request #2788
Opened 2021-08-11 12:37 UTC by Angelii

### PR includes

- [ ] fixed #0
- [ ] add / modify test cases
- [ ] documents, demos

### Screenshot

|  Before  |  After  |
|----|----|
|  ❌  |  ✅  |

2021-08-11 12:41 UTC, visiky commented on src/utils/pattern/dot.ts
> +  cfg: DotPatternCfg | LinePatternCfg | SquarePatternCfg,
直接写成 PatternCfg

2021-08-11 14:58 UTC, visiky requested changes

2021-08-11 14:58 UTC, visiky commented on src/types/pattern.ts
> +  opacity?: number;
注释错误

2021-08-11 14:58 UTC, visiky commented on src/utils/pattern/square.ts
>    context.setTransform(1, 0, 0, 1, 0, 0);
这个主要是？缩放 1 倍？

2021-08-11 14:58 UTC, visiky commented on src/utils/pattern/util.ts
> +  // const pixelRatio = window?.devicePixelRatio || 2;
为什么是测试？ 我印象是可以 work 了？我好像也不是注释掉的了

2021-08-11 15:10 UTC, merged

2021-08-11 15:47 UTC, visiky commented
其他需要待办的：
- [ ] 单测
- [ ] 文档
- [ ] demo（默认不好看、能力是否全部透出：dot、line、square 以及回调方式 以及自定义配置，一些展示即可）
- [ ] 一些 bug，如下：

|||参考|
|---|---|---|
|![image](https://user-images.githubusercontent.com/15646325/129061070-55bde372-3497-4f83-ad19-11a7b20f26ac.png)| 交错似乎又被改坏了，参考 dot |![image](https://user-images.githubusercontent.com/15646325/129061250-14b7eebb-ffd6-4dad-bc95-d05e64b92c8a.png)![image](https://user-images.githubusercontent.com/15646325/129061289-f22fedae-20fc-4d82-be08-276ab13db861.png)|

2021-08-12 02:29 UTC, Angelii commented on src/utils/pattern/square.ts
>    context.setTransform(1, 0, 0, 1, 0, 0);
重置坐标系，让下一个rect绘制不会基于上一个绘制rect时使用的坐标系

2021-08-12 02:37 UTC, Angelii commented on src/utils/pattern/util.ts
> +  // const pixelRatio = window?.devicePixelRatio || 2;
注释掉的部分相当于增大了pattern的canvas画布的面积

canvas.style.width = `${logicalWidth}px`;
canvas.style.height = `${logicalHeight}px`;
上方的代码其实没有起作用，就先保持下方这样的写法了～
canvas.width = width;
canvas.height = height;