fix(heatmap): 修复色力图 coordinate部分配置不起效 和 配置了 refect coordinate 失效的问题
antvis/G2Plot pull request #3294
Opened 2022-07-22 09:31 UTC by ai-qing-hai

- [x] 修复色力图 coordinate部分配置不起效 
- [x] 配置了 refect coordinate 失效的问题

|  Before  |  After  |
|----|----|
|  ![image](https://user-images.githubusercontent.com/65594180/180410159-e7b94076-59e4-4b53-bf74-e46f128b19d7.png)|  ![image.png](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9e64759c661749bd9a2f33b8ab464ddb~tplv-k3u1fbpfcp-watermark.image?) |

2022-07-22 09:36 UTC, hustcc commented on src/plots/heatmap/adaptor.ts
>        type: coordinate.type || 'rect',
'coordinate.type' 也可以删除

2022-07-22 09:37 UTC, hustcc commented on src/plots/heatmap/adaptor.ts
> +    (coordinateController || chart.coordinate()).reflect(reflect);
为什么要单独命名一个变量？

2022-07-22 10:50 UTC, ai-qing-hai commented on src/plots/heatmap/adaptor.ts
> +    (coordinateController || chart.coordinate()).reflect(reflect);
chart.coordinate().reflect(reflect); 会覆盖前面的 coordinate 配置

2022-07-22 10:51 UTC, ai-qing-hai commented on src/plots/heatmap/adaptor.ts
>        type: coordinate.type || 'rect',
已删除

2022-07-25 02:54 UTC, visiky commented on src/plots/heatmap/adaptor.ts
> +    (coordinateController || chart.coordinate()).reflect(reflect);
```ts
const coordinateOption = coordinate ?? { type: 'rect', actions: [] };

if (reflect) {
  coordinateOption.actions.push(['reflect', reflect])
}

chart.coordinate(coordinateOption)
```

2022-07-25 03:08 UTC, ai-qing-hai commented on src/plots/heatmap/adaptor.ts
> +    (coordinateController || chart.coordinate()).reflect(reflect);
已修改

2022-07-25 07:33 UTC, visiky requested changes

2022-07-25 07:33 UTC, visiky commented on src/plots/heatmap/adaptor.ts
> +    (coordinateController || chart.coordinate()).reflect(reflect);
可能还要修改下？
`deepAssign({ actions: [] }, coordinate ?  coordinate : { type:'rect' })`

2022-07-25 07:52 UTC, ai-qing-hai commented
@visiky  我觉得现在的刚刚好， deepAssign  后面的 actions 回覆盖前面的，并没有和  coordinate 叠加， 与其在此修改， 不然现在的代码清晰

2022-07-26 02:34 UTC, ai-qing-hai commented on src/plots/heatmap/adaptor.ts
> +    (coordinateController || chart.coordinate()).reflect(reflect);
我觉得现在的刚刚好， deepAssign 后面的 actions 会覆盖前面的，并没有和 coordinate 的 actions 合并， 与其在此修改， 不如现在的代码清晰。

2022-07-28 08:12 UTC, merged