(feat) 回归散点图增加显示回归拟合函数相关配置，#3474
antvis/G2Plot pull request #3476
Opened 2023-02-22 11:29 UTC by Cuiyansong

### PR includes

- [x] fixed #3474 
- [x] add / modify test cases
- [x] documents, demos

### Screenshot

|  Before  |  After  |
|----|----|
|  ❌  |  ✅  |

✅  
![Uploading antv-regression-equation-snapshot.png…]()

2023-02-23 04:09 UTC, hustcc requested changes

2023-02-23 04:09 UTC, hustcc commented on src/plots/scatter/types.ts
> +  readonly textStyle?: TextStyle;
命名为 equationStyle 会好一点。

2023-02-23 04:09 UTC, hustcc commented on src/plots/scatter/util.ts
>  export const getPath = (config: RenderOptions) => {
这个是 getPath，可以额外提供一个 getEquation 的方法。

2023-02-23 04:09 UTC, hustcc commented on src/plots/scatter/adaptor.ts
> +              text: equation,
@visiky 看看默认的公示放到哪里比较合适。

2023-02-23 04:12 UTC, Cuiyansong commented on src/plots/scatter/types.ts
> +  readonly textStyle?: TextStyle;
👌

2023-02-23 04:13 UTC, Cuiyansong commented on src/plots/scatter/util.ts
>  export const getPath = (config: RenderOptions) => {
没有提供另外一个方法的原因是，计算出pathData后，对应的公式系数也就计算出来了，如果另外再计算的话，会损耗性能。修改方法命名是否合适？

2023-02-23 04:14 UTC, Cuiyansong commented on src/plots/scatter/adaptor.ts
> +              text: equation,
这句话的意思，能详细说一下吗？

2023-02-23 05:50 UTC, visiky commented
这个功能在 G2 5.0 会以组合 mark 的形式实现，在 G2Plot 中把拟合函数作为图表的一个特性挺好的，直接内置到散点图中～

展示样式的话，尽量还是希望可以统一：支持相对定位和绝对定位
- 相对定位，和 path 关联在一起，类似 G2 5.0 中这样：https://g2.antv.antgroup.com/en/examples/analysis/regression/#linear-regression
- 绝对定位，相对画布。PR 的实现就是这类，默认放在左上角也行，不过如果存在多种公式辅助线的话，需要额外的标识来使其对应上

2023-02-23 06:01 UTC, Cuiyansong commented
> 这个功能在 G2 5.0 会以组合 mark 的形式实现，在 G2Plot 中把拟合函数作为图表的一个特性挺好的，直接内置到散点图中～
> 
> 公式展示位置，尽量还是希望可以统一：支持相对定位和绝对定位
> 
> * 相对定位，和 path 关联在一起，类似 G2 5.0 中这样：https://g2.antv.antgroup.com/en/examples/analysis/regression/#linear-regression
> * 绝对定位，相对画布。PR 的实现就是这类，默认放在左上角也行，不过如果存在多种公式辅助线的话，需要额外的标识来使其对应上

1 - 目前PR的实现方式对G2v5版本是否合适？
2 - 相对定位的方式是值用position的hook去自定义位置吗？[参考图表标注功能示例](https://g2plot.antv.antgroup.com/examples/component/annotation/#text-annotation2) 
3 - 绝对定位默认的位置我原本想参考ECharts将公式展示在右上角（折线终点的位置）文本右对齐，只是不是特别熟悉代码，所以就固定了左上角的位置。“如果存在多种公式辅助线的话，需要额外的标识来使其对应上”这一点目前如何做兼容呢？

2023-02-23 06:55 UTC, visiky commented
> > 这个功能在 G2 5.0 会以组合 mark 的形式实现，在 G2Plot 中把拟合函数作为图表的一个特性挺好的，直接内置到散点图中～
> > 公式展示位置，尽量还是希望可以统一：支持相对定位和绝对定位
> > 
> > * 相对定位，和 path 关联在一起，类似 G2 5.0 中这样：https://g2.antv.antgroup.com/en/examples/analysis/regression/#linear-regression
> > * 绝对定位，相对画布。PR 的实现就是这类，默认放在左上角也行，不过如果存在多种公式辅助线的话，需要额外的标识来使其对应上
> 
> 1 - 目前PR的实现方式对G2v5版本是否合适？ 2 - 相对定位的方式是值用position的hook去自定义位置吗？[参考图表标注功能示例](https://g2plot.antv.antgroup.com/examples/component/annotation/#text-annotation2) 。 2.1 - 默认设置，可以改成`position: right`以及`textAlign: end`这种模式，其实这就是我想要的。 2.2 - 需要对外暴露postion属性？`equationPosition：string ｜ Array<string, string>？` 模式是否合适？ 3 - 绝对定位默认的位置我原本想参考ECharts将公式展示在右上角（折线终点的位置）文本右对齐，只是不是特别熟悉代码，所以就固定了左上角的位置。“如果存在多种公式辅助线的话，需要额外的标识来使其对应上”这一点目前如何做兼容呢？

我晚些再回复哈

2023-02-27 06:07 UTC, visiky commented
1、相对定位，即标注和折线图的位置是相对的，效果如 Echarts 和 [G2 5.0 版本](https://g2.antv.antgroup.com/en/examples/analysis/regression#linear-regression)
2、绝对定位，即相对于画布。目前您的实现放置于左上角是没问题的～

2023-02-27 06:14 UTC, Cuiyansong commented
👌，对于这个PR还需要那些地方要修改吗？

2023-02-27 09:01 UTC, visiky commented
> 👌，对于这个PR还需要那些地方要修改吗？

非常感谢你的提交～ 完整 PR 我看了，基于现状的 PR 内容，问题不大，可以按照这个形式。下面是一些小的问题，仅供参考：
1、注释英文的前后留空
2、`equation` 配置，我感觉可以暂时不提供函数回调的方式，等后续丰富之后，回调函数有参数的时候，再行提供

2023-02-27 11:33 UTC, Cuiyansong commented
问题2已经修改完毕，移除对函数的支持。
问题1，能否在Review代码上标注一下，没有get到哪里需要添加“空格”

2023-02-27 11:34 UTC, Cuiyansong commented
问题2已经修改完毕，移除对函数的支持。
问题1，能否在Review代码上标注一下，没有get到哪里需要添加“空格”

2023-03-06 13:22 UTC, Cuiyansong commented
Any update?

2023-03-07 04:12 UTC, hustcc commented on site/docs/api/plots/scatter.zh.md
> +| equation      | string                                                              | 自定义回归方程式，仅在已经自定义`algorithm`以及启用`showEquation`时生效 |
这里，中英文之间的空格。

2023-03-07 04:13 UTC, hustcc commented on src/plots/scatter/adaptor.ts
> +              text: equation,
equation 文本默认放置的位置在哪里？目前是在 [0, 0] 位置吗？

2023-03-07 04:13 UTC, hustcc commented on src/plots/scatter/types.ts
> +   * @description 只有当自定义algorithm时生效
中英文之间的空格。

2023-03-07 04:30 UTC, Cuiyansong commented on src/plots/scatter/adaptor.ts
> +              text: equation,
目前是基于左上角给了x=20，y=20的偏移量，用户可以自定义x、y值

2023-03-07 04:44 UTC, Cuiyansong commented on src/plots/scatter/types.ts
> +   * @description 只有当自定义algorithm时生效
已修改

2023-03-07 05:29 UTC, hustcc approved these changes

2023-03-08 07:15 UTC, merged