fix: 区分dev/dependencies
antvis/G2Plot pull request #3481
Opened 2023-02-27 13:07 UTC by lxfu1

### PR includes

- [ ] fixed #0
- [ ] add / modify test cases
- [ ] documents, demos
- [x] chore 

### Screenshot

|  Before  |  After  |
|----|----|
|  ❌  |  ✅  |

2023-02-27 14:45 UTC, visiky commented on package.json
> +    "@antv/g2": "^5.0.0-beta.5"
不需要依赖～ 目前只是开发依赖

2023-02-27 15:38 UTC, visiky requested changes

2023-02-27 15:38 UTC, visiky commented on jest.node.config.js
> +    '^d3-(.*)$': '<rootDir>/node_modules/d3-$1/dist/d3-$1.min.js',
理论上不需要了？

2023-02-28 08:47 UTC, lxfu1 commented on package.json
> +    "@antv/g2": "^5.0.0-beta.5"
这个还是需要的吧，不是依赖G2吗？

2023-02-28 08:47 UTC, lxfu1 commented on jest.node.config.js
> +    '^d3-(.*)$': '<rootDir>/node_modules/d3-$1/dist/d3-$1.min.js',
我这里不加test过不了，莫非是我用pnpm的原因？

2023-03-09 03:45 UTC, closed without merging