docs: fix link
antvis/G2Plot pull request #3514
Opened 2023-04-05 03:35 UTC by AuroraTea

### PR includes

- [ ] fixed #0
- [ ] add / modify test cases
- [x] documents, demos

### Screenshot

![image](https://user-images.githubusercontent.com/43649460/229974824-48ec5572-5000-4236-8add-167573cb0f1c.png)

2023-05-22 11:22 UTC, hustcc commented on site/docs/manual/upgrade.en.md
> +| Gauge                           | 删除 color 、 min 、 max。<br />删除 value , 改用 percent。 <br />删除 pivot 改用 indicator。 <br /> 更新 range ，详细参考[Gauge](/en/examples/progress-plots/gauge#basic#basic)
这里 basic 重复了吧？

2023-05-22 11:24 UTC, hustcc requested changes

2023-05-22 11:24 UTC, hustcc commented on site/docs/manual/upgrade.en.md
> +| Gauge                           | 删除 color 、 min 、 max。<br />删除 value , 改用 percent。 <br />删除 pivot 改用 indicator。 <br /> 更新 range ，详细参考[Gauge](/en/examples/progress-plots/gauge#basic#basic)
这里 basic 重复了吧？

2023-05-23 00:53 UTC, AuroraTea commented on site/docs/manual/upgrade.en.md
> +| Gauge                           | 删除 color 、 min 、 max。<br />删除 value , 改用 percent。 <br />删除 pivot 改用 indicator。 <br /> 更新 range ，详细参考[Gauge](/en/examples/progress-plots/gauge#basic#basic)
是的是的

2023-05-23 02:32 UTC, hustcc approved these changes

2023-05-23 04:34 UTC, merged